name: graphulus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  flutter_rust_bridge: ^1.75.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  ffigen: ^7.2.10

flutter:
  uses-material-design: true
